kozmos-bank:

  startup-balance: 250

  loan-request:
    minimum-balance: 10000
    maximum-balance: 1000000
    loans:
      car:
        name: '&fCar'
        item: 'MINECART'



  information-message:
    enable: true
    message:
      - ''
      - '&8&l* &fHello &a%name%&f...'
      - '&8&l* &fYour current balance is: &a%player_balance%&f.'
      - '&8&l* &fYou have &a%player_bank_balance%&2$ &fin your bank account.'
      - ''

  storage:
    # mysql || yaml
    type: 'yaml'

  menu:
    size: 27
    title: 'KozmosBank'
    item1:
      display-name: '&fHello &a%name% &e!'
      item: 'BOOK'
      slot: 11
      lore:
        - ''
        - '&fBalance: %player_balance%'
        - '&fBank Balance: %player_bank_balance%'
        - ''