kozmos-bank:
  console:
    data-created: true
  $mysql:
    driver: "com.mysql.cj.jdbc.Driver"
    address: "localhost:3306"
    database: "kozmosbank"
    username: "mixeration"
    password: "password"
    useSSL: false
  information-message:
    enable: true
    message:
      - ''
      - '&8&l* &fHello &a%name%&f...'
      - '&8&l* &fYour current balance is: &a%player_balance%&f.'
      - '&8&l* &fYou have &a%player_bank_balance%&2$ &fin your bank account.'
      - ''
  storage: mysql